# Generated by Django 4.0.5 on 2022-06-25 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, editable=False, max_length=32, unique=True, verbose_name='Site (name of Django app)')),
                ('git_repo', models.CharField(blank=True, help_text="\n            <div style='line-height:1.15rem'>\n                <b>git@github.com:&lt;username&gt;/&lt;repo&gt</b>\n                or whatever you'd use with git clone.<br />\n                If you've set up an SSH key and use Git over SSH, everything should work.\n            </div>\n        ", max_length=2048, null=True, verbose_name='Git repository (for automatic git push)')),
                ('site_root', models.URLField(blank=True, help_text="\n            <div style='line-height:1.15rem'>\n                Usually something like <b>https://yourdomain.com</b><br />\n                Recommended but optional unless the site is served from a subdirectory.<br />\n                Also useful for certain meta tags.\n            </div>\n        ", null=True, verbose_name='Root URL of the production site')),
                ('auto_publish_wait', models.PositiveSmallIntegerField(default=5, help_text="\n            <div style='line-height:1.15rem'>\n                Will wait this many minutes after the last update before publishing.<br />\n                Set to 0 to always publish immediately.\n            </div>\n        ", verbose_name='Auto publish after last update (minutes)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_published', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), editable=False)),
            ],
        ),
    ]
