# Generated by Django 4.0.5 on 2022-06-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=64)),
                ('header_image', models.ImageField(upload_to='static/mars/uploads')),
                ('about_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/mars/uploads/albums')),
                ('link', models.URLField()),
                ('album_id', models.CharField(max_length=64, unique=True, verbose_name='Album ID (Bandcamp)')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='mars.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
